FROM python:3.9-slim

WORKDIR /app

RUN python3 -m venv /app/venv

ENV PATH="/app/venv/bin:$PATH"

RUN  --mount=type=bind,source=requirements.txt,target=/app/requirements.txt \
    pip install --upgrade pip \
    && pip install -r /app/requirements.txt

COPY . .

CMD ["python", "main.py"]
