version: '3.8'

include:
  - ./proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: web:latest
    container_name: web
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_USER_PASSWORD}
      - DB_NAME=${MYSQL_DB}
    restart: always

  db:
    image: mysql:8
    container_name: db
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_USER_PASSWORD}
    restart: always

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s
      disable: false
