version: "3"
include:
    - docker-compose.yaml
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9000:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
